name: DeepProfessions
description: $description
version: '$version'

main: com.ShibuiKaleb.deepProfessions.DeepProfessions
api-version: '1.21.11'
load: POSTWORLD

authors: [ ShibuiKaleb ]

commands:
  profession:
    description: Manage your profession
    usage: /profession <choose|change|confirm>
  dpadmin:
    description: DeepProfessions admin commands
    usage: /dpadmin <setlevel>